apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.web.name }}
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30800
  selector:
    components: {{ .Values.web.name }}
